import { getDatabaseProvider } from "./provider";
import * as sqliteApp from "./app.schema";
import * as sqliteAudit from "./audit.schema";
import * as sqliteSam from "./sam.schema";
import * as sqliteAuth from "./better-auth-schema";
import * as sqliteBilling from "./billing.schema";
import * as sqliteGsc from "./gsc.schema";
import * as sqliteReddit from "./reddit-attribution.schema";
import * as sqliteTelemetry from "./telemetry.schema";
// MORGANA LOCAL PATCH (UPSTREAM.md, patch P6).
import * as sqliteSearchIntelligence from "./search-intelligence.schema";
import * as sqliteSearchIntelligenceP2 from "./search-intelligence-p2.schema";
import * as sqliteSearchIntelligenceP3 from "./search-intelligence-p3.schema";
import * as sqliteSearchIntelligenceP3Jobs from "./search-intelligence-p3-jobs.schema";
import * as sqliteSearchIntelligenceP4 from "./search-intelligence-p4.schema";
import * as sqliteSearchIntelligenceP5 from "./search-intelligence-p5.schema";
import * as sqliteSearchIntelligenceP5Ai from "./search-intelligence-p5-ai.schema";
import * as pgApp from "./pg/app.schema";
import * as pgAudit from "./pg/audit.schema";
import * as pgSam from "./pg/sam.schema";
import * as pgAuth from "./pg/better-auth-schema";
import * as pgBilling from "./pg/billing.schema";
import * as pgGsc from "./pg/gsc.schema";
import * as pgReddit from "./pg/reddit-attribution.schema";
import * as pgTelemetry from "./pg/telemetry.schema";
import * as pgSearchIntelligence from "./pg/search-intelligence.schema";
import * as pgSearchIntelligenceP2 from "./pg/search-intelligence-p2.schema";
import * as pgSearchIntelligenceP3 from "./pg/search-intelligence-p3.schema";
import * as pgSearchIntelligenceP3Jobs from "./pg/search-intelligence-p3-jobs.schema";
import * as pgSearchIntelligenceP4 from "./pg/search-intelligence-p4.schema";
import * as pgSearchIntelligenceP5 from "./pg/search-intelligence-p5.schema";
import * as pgSearchIntelligenceP5Ai from "./pg/search-intelligence-p5-ai.schema";

// Canonical schema barrel. Repositories import their tables from here and the
// provider-aware `db` from "@/db", so each repository is written ONCE for both
// backends.
//
// The TYPE identity is the SQLite definitions; the runtime VALUES are whichever
// provider is active. `schema-parity.test.ts` asserts the two dialect schemas
// are structurally interchangeable (same tables/columns/nullability/PKs/unique
// indexes), which is what makes the single cast below sound. The Postgres
// schema is the one structural artifact NOT regenerated by `db:generate`, so the
// parity test is its drift guard.
type AppSchema = typeof sqliteApp &
  typeof sqliteAudit &
  typeof sqliteSam &
  typeof sqliteAuth &
  typeof sqliteBilling &
  typeof sqliteGsc &
  typeof sqliteReddit &
  typeof sqliteTelemetry &
  typeof sqliteSearchIntelligence &
  typeof sqliteSearchIntelligenceP2 &
  typeof sqliteSearchIntelligenceP3 &
  typeof sqliteSearchIntelligenceP3Jobs &
  typeof sqliteSearchIntelligenceP4 &
  typeof sqliteSearchIntelligenceP5 &
  typeof sqliteSearchIntelligenceP5Ai;

const runtimeSchema =
  getDatabaseProvider() === "postgres"
    ? {
        ...pgApp,
        ...pgAudit,
        ...pgSam,
        ...pgAuth,
        ...pgBilling,
        ...pgGsc,
        ...pgReddit,
        ...pgTelemetry,
        ...pgSearchIntelligence,
        ...pgSearchIntelligenceP2,
        ...pgSearchIntelligenceP3,
        ...pgSearchIntelligenceP3Jobs,
        ...pgSearchIntelligenceP4,
        ...pgSearchIntelligenceP5,
        ...pgSearchIntelligenceP5Ai,
      }
    : {
        ...sqliteApp,
        ...sqliteAudit,
        ...sqliteSam,
        ...sqliteAuth,
        ...sqliteBilling,
        ...sqliteGsc,
        ...sqliteReddit,
        ...sqliteTelemetry,
        ...sqliteSearchIntelligence,
        ...sqliteSearchIntelligenceP2,
        ...sqliteSearchIntelligenceP3,
        ...sqliteSearchIntelligenceP3Jobs,
        ...sqliteSearchIntelligenceP4,
        ...sqliteSearchIntelligenceP5,
        ...sqliteSearchIntelligenceP5Ai,
      };

// oxlint-disable-next-line typescript/no-unsafe-type-assertion -- guarded by schema-parity.test.ts
const schema = runtimeSchema as unknown as AppSchema;

export const {
  userOnboardingAnswers,
  projects,
  savedKeywords,
  savedKeywordTags,
  savedKeywordTagAssignments,
  keywordMetrics,
  rankTrackingConfigs,
  rankTrackingKeywords,
  rankCheckRuns,
  rankSnapshots,
  organizationActivationState,
  projectActivationState,
  backlinkSnapshots,
  audits,
  auditPages,
  auditLinks,
  auditIssues,
  auditLighthouseResults,
  samSessions,
  samProjectMemory,
  user,
  session,
  account,
  verification,
  organization,
  member,
  invitation,
  billingCustomerStatus,
  gscConnections,
  redditAttributions,
  telemetryState,
  // MORGANA LOCAL PATCH (UPSTREAM.md, patch P6).
  searchEntities,
  domainSnapshots,
  domainSnapshotKeywords,
  domainSnapshotPages,
  domainRefreshJobs,
  searchUsageLedger,
  searchBudgetState,
  // MORGANA LOCAL PATCH (UPSTREAM.md, patch P7).
  keywordClusters,
  trackedKeywords,
  siRankSnapshots,
  keywordGapSnapshots,
  shareOfSearchSnapshots,
  rankingEvents,
  rankingJobs,
  phase2UsageLedger,
  // MORGANA LOCAL PATCH (UPSTREAM.md, patch P12).
  siRankTasks,
  // MORGANA LOCAL PATCH (UPSTREAM.md, patch P8).
  siBacklinks,
  siBacklinkSnapshots,
  siReferringDomains,
  siAnchorSnapshots,
  siBacklinkEvents,
  siBacklinkUsageLedger,
  siBacklinkJobs,
  siBacklinkGapSnapshots,
  // MORGANA LOCAL PATCH (UPSTREAM.md, patch P9).
  siGraphNodes,
  siGraphEdges,
  siGraphEvidence,
  siCampaigns,
  siCampaignSignals,
  siReputationFindings,
  siTimelineEvents,
  siCorrelationCheckpoints,
  // MORGANA LOCAL PATCH (UPSTREAM.md, patch P10).
  siSiteAuditRuns,
  siSiteAuditFrontier,
  siSiteAuditPages,
  siSiteAuditLinks,
  siSiteAuditIssues,
  siSiteAuditIssueEvents,
  siSiteAuditUsageLedger,
  siAiVisibilityQueries,
  siAiVisibilitySnapshots,
  siAiVisibilityCitations,
  siAiVisibilityEvents,
} = schema;
